### PR TITLE
Branding env prefixed with APP, light/dark logos, HeltSikker images

### PR DESCRIPTION
**Pull request by skivdal**
Changes a few things:

- Environment variables to be customized in prod had to be prefixed with APP
- Different logos for light and dark mode (HeltSikker logos requires this)
- Images to be hosted for HeltSikker's branding
- Added the dynamic branding env vars to frontend/src/vite-env.d.ts

Looks like this now with the appropiate env for HeltSikker:
image
image

Does not affect the default style.

### CODE REVIEW

**Review by mathiash98 — APPROVED** [review]
Great

**Comment by nheek** [comment]
why with APP prefix?

**Comment by skivdal** [comment]
If you look at frontend/docker-entrypoint.sh it only includes environment variables prefixed with APP to the production frontend

**Comment by nheek** [comment]
I see, thank you!

**Pull request merged**
